
version: '3.1'
services:
    redis:
      image: 'redis:alpine'
      container_name: 'tray-redis'

    mysql:
        image: 'mysql:5.7'
        container_name: 'tray-mysql'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tray
            - MYSQL_USER=user
            - MYSQL_PASSWORD=root
        ports:
            - '8001:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: 'tray-nginx'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8084:80'

    php-fpm:
        image: viniciusponce/tray-programmer
        container_name: 'tray-phpfpm'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini'
